// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("kIsWEB");
      return web;
    }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAYaoRTfxxId479-5D989w_7UFEI172Oo8",
  authDomain: "shopping-45cf6.firebaseapp.com",
  projectId: "shopping-45cf6",
  storageBucket: "shopping-45cf6.appspot.com",
  messagingSenderId: "598599070096",
  appId: "1:598599070096:web:afd82e3a8d4825aaa9c315",
  measurementId: "G-7983QSSQKK"
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCT0sdbRCjpshbkN81iK6d7crl46Y4qOWQ',
  //   appId: '1:403715982561:android:1b7b341e5a75b00611a3a0',
  //   messagingSenderId: '403715982561',
  //   projectId: 'tailoringapp-3bac6',
  //   storageBucket: 'tailoringapp-3bac6.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAAEqAHLLoOMGYDlnINUyLwLM9Yuo_RmZ0',
  //   appId: '1:403715982561:ios:dc8680d38857f20911a3a0',
  //   messagingSenderId: '403715982561',
  //   projectId: 'tailoringapp-3bac6',
  //   storageBucket: 'tailoringapp-3bac6.appspot.com',
  //   iosBundleId: 'com.example.tailoringApp',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAAEqAHLLoOMGYDlnINUyLwLM9Yuo_RmZ0',
  //   appId: '1:403715982561:ios:a9b46ff96b36f9b811a3a0',
  //   messagingSenderId: '403715982561',
  //   projectId: 'tailoringapp-3bac6',
  //   storageBucket: 'tailoringapp-3bac6.appspot.com',
  //   iosBundleId: 'com.example.tailoringApp.RunnerTests',
  // );
}
